CREATE TABLE TBL_TEAM
(
	[ID] INT NOT NULL IDENTITY(1,1),
	[NAME] VARCHAR(50) NOT NULL,
	[QUALITY_BENCHMARK] VARCHAR(50) NOT NULL,
	[VERSION] INT NOT NULL DEFAULT(1),
	[LAST_MODIFIED_AT] DATETIME NOT NULL DEFAULT(GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(50) NOT NULL
	CONSTRAINT [PK_TBL_TEAM] PRIMARY KEY ([ID]),
)

 