USE [HWQATOOL]
GO
IF OBJECT_ID('dbo.TBL_TEAM', 'U') IS NOT NULL 
BEGIN
  DROP TABLE dbo.TBL_TEAM; 
END
GO
CREATE TABLE dbo.TBL_TEAM
(
	[ID] INT NOT NULL IDENTITY(1,1),
	[NAME] VARCHAR(50) NOT NULL,
	[QUALITY_BENCHMARK] DECIMAL(5,2) NOT NULL,
	[IS_ACTIVE] BIT NOT NULL DEFAULT(1),
	[VERSION] INT NOT NULL DEFAULT(1),
	[LAST_MODIFIED_AT] DATETIME NOT NULL DEFAULT(GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(50) NOT NULL
	CONSTRAINT [PK_TBL_TEAM] PRIMARY KEY ([ID]),
	CONSTRAINT [UQ_TBL_TEAM_NAME] UNIQUE ([NAME])
)
GO
