

CREATE TABLE [DBO].[TBL_AUDIT_TIME_SLOT](
	[ID] INT NOT NULL IDENTITY (1,1),
	[AUDIT_ID] INT NOT NULL,
	[AUDITOR] VARCHAR(50) NOT NULL,
	[START_DATE] DATETIME NOT NULL,
	[END_DATE] DATETIME NOT NULL,
	[TOTAL_TIME] DATETIME NOT NULL,
	[STATUS] VARCHAR(20) NULL,
	[VERSION] INT NOT NULL DEFAULT(1),
	[LAST_MODIFIED_AT] DATETIME NOT NULL DEFAULT (GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(50)NOT NULL,
	CONSTRAINT [PK_TBL_AUDIT_TIME_SLOT] PRIMARY KEY([ID]),
	CONSTRAINT[UQ_TBL_AUDIT_TIME_SLOT_AUDIT_ID_AUDITOR] UNIQUE([AUDIT_ID],[AUDITOR]),
	CONSTRAINT[FK_TBL_AUDIT_TIME_SLOT_AUDIT_ID_TBL_AUDIT_ID] FOREIGN KEY([AUDIT_ID]) REFERENCES TBL_AUDIT([ID])
	)

GO

SET ANSI_PADDING OFF
GO


