USE [Qa tool]
GO

/****** Object:  Table [dbo].[tblAudit]    Script Date: 06/02/2017 12:23:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [DBO].[TBL_AUDIT](
	[ID] INT NOT NULL,
	[AUDITID] VARCHAR(50) NULL,
	[AUDITOR] VARCHAR(50) NULL,
	[STARTDATE] DATETIME NULL,
	[ENDDATE] DATETIME NULL,
	[TOTALTIME] DATETIME NULL,
	[STATUS] VARCHAR(20) NULL,
	[VERSION] INT NOT NULL DEFAULT(1),
	[LASTMODIFIEDAT] DATETIME NOT NULL DEFAULT (GETDATE()),
	[LASTMODIFIEDBY] VARCHAR(50)NOT NULL,
	CONSTRAINT [PK_TBL_AUDIT] PRIMARY KEY([ID]),
	CONSTRAINT[UQ_TBL_AUDIT_LASTMODIFIEDAT_LASTMODIFIEDBY] UNIQUE([LASTMODIFIEDAT],[LASTMODIFIEDBY]),
	CONSTRAINT[FK_TBL_AUDIT_TBL_USER_ID] FOREIGN KEY([AUDITID]) REFERENCES TBL_USER([ID])
	)

GO

SET ANSI_PADDING OFF
GO


