USE [HWQATOOL]
GO
IF OBJECT_ID('DBO.TBL_AUDIT_TIME_SLOT', 'U') IS NOT NULL 
BEGIN
  DROP TABLE [DBO].[TBL_AUDIT_TIME_SLOT]
END
GO
CREATE TABLE [DBO].[TBL_AUDIT_TIME_SLOT]
(
	[ID] BIGINT NOT NULL,
	[AUDIT_ID] INT NOT NULL,
	[AUDITOR] INT NOT NULL,
	[START_DATE] DATETIME NOT NULL,
	[END_DATE] DATETIME NULL,	
	[STATUS] INT NOT NULL,
	[VERSION] INT NOT NULL DEFAULT(1),
	[LAST_MODIFIED_AT] DATETIME NOT NULL DEFAULT (GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_TBL_AUDIT_TIME_SLOT] PRIMARY KEY([ID]),
	CONSTRAINT[FK_TBL_AUDIT_TIME_SLOT_TBL_AUDIT_ID] FOREIGN KEY([AUDIT_ID]) REFERENCES [TBL_AUDIT]([ID]),
	CONSTRAINT[FK_TBL_AUDIT_TIME_SLOT_TBL_USER_ID] FOREIGN KEY([AUDITOR]) REFERENCES [TBL_USER]([ID])
)
GO
