create table tblTeam(Id int,Name Varchar(20),QualityBenchMark varchar(20),[Version] int,LastModifiedAt date,LastModifiedBy varchar(20));

create table tblAuditTimeSlot(Id int,AuditId int,Auditor varchar(20),StartDate date,EndDate date,TotalTime Time,[status] bit,[Version] int,LastModifiedAt date,LastModifiedBy varchar(20));   

CREATE TABLE TBLAUDIT
(
[ID] INT NOT NULL IDENTITY(1,1),
[AUDITNO] INT NOT NULL,
[CONFIRMATIONNO] INT NOT NULL,
[SERVICEREQUESTNO] INT NOT NULL,
[PROCESSEDDATE] DATE NOT NULL,[PROCESSOR] VARCHAR(20)NOT NULL,
[CLIENTID] INT NOT NULL,
[SUBTASKID] INT NOT NULL,
[TASKID] INT NOT NULL,
[AUDITOR] VARCHAR(20)NOT NULL,
[AUDITDATE] DATE NOT NULL,
[COMMENTS] VARCHAR(20)NOT NULL,
[ISDEFECT] BIT NOT NULL,
[ISLEARNING] BIT NOT NULL,
[ISESCALATION] BIT NOT NULL,
[ISCLIENTFOCUS] BIT NOT NULL,
[ISDUPLICATE] BIT NOT NULL,
[ISSAMPLED] BIT NOT NULL,
[NOOFRECORDS] INT NOT NULL,
[TOTALDEFECTS] INT NOT NULL,
[STATUS] VARCHAR(20)NOT NULL,
[PLATFORMID] INT NOT NULL,
[VERSION] INT NOT NULL,
[LASTMODIFIEDAT] DATE NOT NULL,
[LASTMODIFIEDBY] VARCHAR(20)NOT NULL
CONSTRAINT [PK_TBL_GRADE] PRIMARY KEY ([ID]),
CONSTRAINT [UQ_TBL_GRADE_TEAM_ID_NAME] UNIQUE ([ID],[CLIENTID]),
);