USE [HWQATOOL]
GO
IF OBJECT_ID('DBO.TBL_EXCEL_RECORD', 'U') IS NOT NULL 
BEGIN
  DROP TABLE [DBO].[TBL_EXCEL_RECORD]
END
GO
CREATE TABLE [DBO].[TBL_EXCEL_RECORD]
(
	[ID] BIGINT NOT NULL IDENTITY(1,1),
	[TEAM_ID] INT NOT NULL,
	[IS_ERROR] BIT NOT NULL DEFAULT(0),
	[ERROR_CODE] VARCHAR(MAX) NULL,
	[CLIENT] VARCHAR(50) NULL,
	[TASK] VARCHAR(50) NULL,
	[PLATFORM] VARCHAR(50) NULL,
	[PROCESSOR] VARCHAR(50) NULL,
	[PROCESSDATE] VARCHAR(50) NULL,
	[SERVICE_REQUEST_NO] VARCHAR(50) NULL,
	[AUDIT_NO] VARCHAR(50) NULL,
	[BATCH_NO] VARCHAR(50) NULL,
	[FILE_NO] VARCHAR(50) NULL,
	[NO_OF_RECORDS] VARCHAR(50) NULL,
	[AUDITOR] VARCHAR(50) NULL,	
	CONSTRAINT [FK_TBL_EXCEL_RECORD_TEAM_ID_TBL_TEAM_ID] FOREIGN KEY ([TEAM_ID]) REFERENCES TBL_TEAM([ID])	
)
GO
