USE [QA TOOL]
GO

/****** OBJECT:  TABLE [DBO].[TBLUSER]    SCRIPT DATE: 06/02/2017 14:36:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [DBO].[TBL_USER](
	[ID] INT NOT NULL,
	[LOGINID] VARCHAR(50) NULL,
	[EMAIL] VARCHAR(20) NULL,
	[FIRSTNAME] VARCHAR(20) NULL,
	[LASTNAME] VARCHAR(20) NULL,
	[LOCATION] VARCHAR(20) NULL,
	[SUPERVOISEREMAIL] VARCHAR(20) NULL,
	[GRADEID] VARCHAR(50) NULL,
	[SAMPLEPERCENTAGE] DECIMAL(5, 2) NULL,
	[ISACTIVE] VARCHAR(20) NULL,
	[COMMENTS] VARCHAR(20) NULL,
	[VERSION] INT NOT NULL,
	[LASTMODIFIEDAT] DATETIME NULL DEFAULT (GETDATE()),
	[LASTMODIFIEDBY] VARCHAR(20) NULL
	CONSTRAINT [PK_TBL_USER] PRIMARY KEY([ID]),
	CONSTRAINT[UQ_TBL_USER_EMAIL_LOGINID] UNIQUE ([EMAIL],[LOGINID]),
	CONSTRAINT[FK_TBL_USER_TBL_USER_ID] FOREIGN KEY([GRADEID]) REFERENCES TBL_GRADE([ID])
	)
 ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


