USE [HWQATOOL]
GO
IF OBJECT_ID('dbo.TBL_USER', 'U') IS NOT NULL 
BEGIN
  DROP TABLE [DBO].[TBL_USER]
END
GO
CREATE TABLE [DBO].[TBL_USER]
(
	[ID] INT NOT NULL IDENTITY(1,1),
	[LOGIN_ID] VARCHAR(50) NOT NULL ,
	[EMAIL] VARCHAR(20) NOT NULL ,
	[FIRST_NAME] VARCHAR(20) NOT NULL ,
	[LAST_NAME] VARCHAR(20) NOT NULL ,
	[LOCATION] VARCHAR(20) NOT NULL ,
	[SUPERVOISER_EMAIL] VARCHAR(20) NULL,
	[GRADE_ID] INT NOT NULL ,
	[SAMPLE_PERCENTAGE] DECIMAL(5, 2) NOT NULL ,
	[IS_ACTIVE] BIT NOT NULL,
	[COMMENTS] VARCHAR(20) NULL,
	[VERSION] INT NOT NULL DEFAULT (1),
	[LAST_MODIFIED_AT] DATETIME NULL DEFAULT (GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(20) NOT NULL,
	CONSTRAINT [PK_TBL_USER] PRIMARY KEY([ID]),
	CONSTRAINT[UQ_TBL_USER_EMAIL] UNIQUE ([EMAIL]),
	CONSTRAINT[UQ_TBL_USER_LOGIN_ID] UNIQUE ([LOGIN_ID]),
	CONSTRAINT[FK_TBL_USER_GRADE_ID_TBL_GRADE_ID] FOREIGN KEY ([GRADE_ID]) REFERENCES TBL_GRADE([ID])
)
GO
