USE [HWQATOOL]
GO
IF OBJECT_ID('dbo.TBL_SUB_TASK', 'U') IS NOT NULL 
BEGIN
  DROP TABLE dbo.[TBL_SUB_TASK]
END
GO
CREATE TABLE [TBL_SUB_TASK]
(
	[ID] INT NOT NULL IDENTITY(1,1),
	[NAME] VARCHAR(50) NOT NULL,
	[TASK_ID] INT NOT NULL,
	[IS_ACTIVE] BIT NOT NULL DEFAULT(1),
	[VERSION] INT NOT NULL DEFAULT(1),
	[LAST_MODIFIED_AT] DATETIME NOT NULL DEFAULT(GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_TBL_SUB_TASK] PRIMARY KEY ([ID]),
	CONSTRAINT [UQ_TBL_SUB_TASK_TASK_ID_NAME] UNIQUE ([TASK_ID],[NAME]),
	CONSTRAINT [FK_TBL_SUB_TASK_TASK_ID_TBL_TASK_ID] FOREIGN KEY ([TASK_ID]) REFERENCES [TBL_TASK] ([ID])
)
GO
