    -- EXEC SP_AUDITS @BATCH_NO = NULL
   Alter PROC SP_AUDITS
	@BATCH_NO varchar(50) = NULL,
	@AUDIT_NO varchar(50)=NULL,
	@CLIENT VARCHAR(50)=NULL,
	@PROCESSOR VARCHAR(50)=NULL,
	@AUDITOR VARCHAR(50)=NULL,	
	@TYPE VARCHAR(50) = NULL,
	@STATUS INT=null,
	@ERROR VARCHAR(50)=NULL,
	@NO_OF_RECORDS INT=null,
	@AUDITOR_COMMENTS VARCHAR(50)=NULL,
	@IS_DEFECT BIT=null,
	@KEY_CLIENT VARCHAR(50)=NULL,
	@PLATFORM1 VARCHAR(50)=NULL,
	@AUDIT_FROM DATETIME = '1/1/1753',
	@AUDIT_TO DATETIME='12/31/9999',
	@PROCESSED_FROM DATETIME= '1/1/1753',
	@PROCESSED_TO DATETIME='12/31/9999',
    @SERVICE_REQUEST_NO VARCHAR(50)=NULL,
    @FILE_NO VARCHAR(50)=NULL
	AS
  BEGIN
	SELECT 
		BATCH_NO,
		AUDIT_NO,
		PROCESSED_DATE, 
		AUDIT_DATE,
		C.NAME AS CLIENT,
		P.FIRST_NAME AS PROCESSOR,
		AU.FIRST_NAME AS AUDITOR,
		E.NAME AS ERROR,
		C.IS_KEY_CLIENT AS KEY_CLIENT,		 
		T.[NAME] AS TYPE,
		[STATUS],		 
		NO_OF_RECORDS,
		PT.NAME AS PLATFORM1,
		IS_DEFECT,
		AUDITOR_COMMENTS,
		SERVICE_REQUEST_NO,
		FILE_NO
	FROM
	dbo.TBL_AUDIT A 
	LEFT JOIN dbo.TBL_CLIENT C ON A.CLIENT_ID = C.ID
	LEFT JOIN  dbo.TBL_PLATFORM PT ON A.PLATFORM_ID = PT.ID
	LEFT JOIN  dbo.TBL_USER P ON A.PROCESSOR = P.ID
	LEFT JOIN  dbo.TBL_USER AU ON A.PROCESSOR = AU.ID
	LEFT JOIN  dbo.TBL_SUB_TASK T ON A.SUB_TASK_ID = T.ID
	LEFT JOIN  dbo.TBL_AUDIT_FINDING AF ON A.ID = AF.AUDIT_ID
	LEFT JOIN  dbo.TBL_ERROR E ON E.ID = AF.ERROR_ID
	WHERE 
	    BATCH_NO LIKE '%'+ISNULL(@BATCH_NO,'')+'%'
	AND AUDIT_NO LIKE '%'+ISNULL(@AUDIT_NO,'')+'%'
    AND PT.ID= ISNULL(@PLATFORM1,PT.ID)
    AND C.ID=ISNULL(@CLIENT,C.ID)
    AND P.ID=ISNULL(@PROCESSOR,P.ID)
    AND AU.ID=ISNULL(@AUDITOR,AU.ID)
    AND T.ID=ISNULL(@TYPE,T.ID)
    AND E.ID=ISNULL(@ERROR,E.ID)
    AND NO_OF_RECORDS=ISNULL(@NO_OF_RECORDS,NO_OF_RECORDS)
    AND AUDITOR_COMMENTS=ISNULL(@AUDITOR_COMMENTS,AUDITOR_COMMENTS)
    AND IS_DEFECT=ISNULL(@IS_DEFECT,IS_DEFECT)
    AND [STATUS]=ISNULL(@STATUS,[STATUS])
    AND C.ID=ISNULL(@KEY_CLIENT,C.ID)
	AND AUDIT_DATE  BETWEEN @AUDIT_FROM AND @AUDIT_TO
	AND PROCESSED_DATE  BETWEEN @PROCESSED_FROM AND @PROCESSED_TO  
	AND SERVICE_REQUEST_NO=ISNULL(@SERVICE_REQUEST_NO,SERVICE_REQUEST_NO) 
	AND FILE_NO=ISNULL(@FILE_NO,FILE_NO)
END;
