CREATE TABLE [TBL_SUBTASK]
(
[ID] INT, NOT NULL IDENTITY (1,1),
[NAME] VARCHAR (50) NOT NULL,
[TASKID] INT,NOT NULL,
[VERSION] INT,NOT NULL DEFAULT(1),
[LASTMODIFIEDAT] DATETIME,NOT NULL DEFAULT(GETDATE()),
[LASTMODIFIEDBY] VARCHAR(50),NOTNULL,
 )
