CREATE TABLE [TBL_SUBTASK]
(
	[ID] INT NOT NULL IDENTITY(1,1),
	[TASK_ID] INT NOT NULL,
	[NAME] VARCHAR (50) NOT NULL,
	[VERSION] INT NOT NULL DEFAULT(1),
	[LAST_MODIFIED_AT] DATETIME NOT NULL DEFAULT(GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_TBL_SUBTASK] PRIMARY KEY ([ID]),
	CONSTRAINT [UQ_TBL_SUBTASK_TASK_ID_NAME] UNIQUE ([TASK_ID],[NAME]),
	CONSTRAINT [FK_TBL_SUBTASK_TASK_ID_TBL_TASK_ID] FOREIGN KEY ([TASK_ID]) REFERENCES TBL_TASK ([ID])
)+
