CREATE TABLE [TBL_USER_ROLE]
([ID] INT NOT NULL IDENTITY(1,1),
[USER_ID] INT NOT NULL,
[ROLE] VARCHAR(50) NOT NULL,
[VERSION] INT NOT NULL DEFAULT(1),
[LAST_MODIFIED_AT] DATETIME NOT NULL DEFAULT(GETDATE()),
[LAST_MODIFIED_BY] VARCHAR(50) NOT NULL,
CONSTRAINT [PK_TBL_USER_ROLE] PRIMARY KEY ([ID]),
CONSTRAINT [UQ_TBL_USER_ROLE_ROLE_USER_ID] UNIQUE ([ROLE],[USER_ID]),
CONSTRAINT [FK_TBL_USER_ROLE_USER_ID_TBL_USER_ID] FOREIGN KEY ([USER_Id]) REFERENCES TBL_USER ([ID]))